/**
 * sync-semantic-enums.ts
 *
 * Reads enum-bearing columns from the database and generates TypeScript
 * modules that mirror them. Run in pre-commit or CI so the semantic layer
 * contract follows the schema, not the documentation.
 *
 * Usage:
 *   npx tsx scripts/sync-semantic-enums.ts
 *
 * Effect: writes one file per (table, column) pair under
 * lib/analytics/semantic/generated/.
 */

import { createClient } from '@supabase/supabase-js'
import { writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

// Service-role client — read-only is enough but service-role bypasses RLS
// which is what you want for a contract sync. Replace with your own client.
const admin = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

const targets = [
  ['echeances_inscription', 'statut'],
  ['inscriptions', 'statut'],
  ['contacts', 'statut'],
] as const

const outDir = path.join(process.cwd(), 'lib/analytics/semantic/generated')
mkdirSync(outDir, { recursive: true })

for (const [table, col] of targets) {
  const { data, error } = await admin.from(table).select(col)
  if (error) throw new Error(`${table}.${col}: ${error.message}`)
  const values = [...new Set(data?.map((r) => r[col]).filter(Boolean))].sort()
  const out = `// generated by scripts/sync-semantic-enums.ts — DO NOT EDIT
export const ${table}_${col}_enum = ${JSON.stringify(values)} as const
export type ${table}_${col}_value = typeof ${table}_${col}_enum[number]
`
  writeFileSync(path.join(outDir, `${table}.${col}.ts`), out)
  console.log(`✓ ${table}.${col}: ${values.length} values written`)
}
